# Generated by Django 3.2.7 on 2021-11-27 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_auto_20211127_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
