# Generated by Django 3.2.7 on 2021-11-27 14:14

import comic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_alter_comic_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='comic',
            name='main_image',
            field=models.ImageField(max_length=500, upload_to=comic.models.comic_images_directory_path),
        ),
        migrations.AlterField(
            model_name='comic',
            name='other_image1',
            field=models.ImageField(blank=True, max_length=500, upload_to=comic.models.comic_images_directory_path),
        ),
        migrations.AlterField(
            model_name='comic',
            name='other_image2',
            field=models.ImageField(blank=True, max_length=500, upload_to=comic.models.comic_images_directory_path),
        ),
    ]
