# Generated by Django 3.2.7 on 2021-12-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('comic', '0004_alter_comic_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Volume/Series', 'verbose_name_plural': 'Volumes/Series'},
        ),
        migrations.RemoveField(
            model_name='comic',
            name='year',
        ),
        migrations.AlterField(
            model_name='comic',
            name='art_by',
            field=models.ManyToManyField(blank=True, related_name='All_Artists', to='comic.Talent'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='written_by',
            field=models.ManyToManyField(blank=True, related_name='All_Writers', to='comic.Talent'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='volume_slug',
            field=models.SlugField(unique=True, verbose_name='Volume/Series Slug'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='volume_title',
            field=models.CharField(max_length=255, verbose_name='Volume/Series Name'),
        ),
        migrations.DeleteModel(
            name='Annual',
        ),
    ]
