# Generated by Django 3.2.7 on 2021-11-24 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('delivery_charges', models.IntegerField(blank=True, default=10)),
                ('delivery_status', models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Delivered'), (3, 'Failed')], default=1)),
                ('payment_status', models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Done'), (3, 'Failed')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comic', models.ManyToManyField(blank=True, to='comic.Comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='LoginCart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('subtotal', models.IntegerField(blank=True, default=0)),
                ('comic', models.ManyToManyField(blank=True, to='comic.Comic')),
            ],
            options={
                'verbose_name': 'Login Cart',
                'verbose_name_plural': 'Login Cart',
            },
        ),
    ]
